[package]
name = "shzhrs"
version = "0.1.0"
authors = ["David Hewson <rust@daveid.co.uk>"]

[dependencies]
rand = "0.4.2"
smallvec = "0.6.0"
pathfinding = "0.6.11"

[dev-dependencies]
rayon = "1.0.0"
ansi_term = "0.11"
criterion = "0.2.1"

[[bench]]
name = "criterion_benchmark"
harness = false
